package zjc.zhixun.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zjc.zhixun.db.domain.ZhiXunRole;
import zjc.zhixun.db.domain.ZhiXunRoleExample;

public interface ZhiXunRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role
     *
     * @mbg.generated
     */
    long countByExample(ZhiXunRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role
     *
     * @mbg.generated
     */
    int deleteByExample(ZhiXunRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role
     *
     * @mbg.generated
     */
    int insert(ZhiXunRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role
     *
     * @mbg.generated
     */
    int insertSelective(ZhiXunRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role
     *
     * @mbg.generated
     */
    ZhiXunRole selectOneByExample(ZhiXunRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role
     *
     * @mbg.generated
     */
    ZhiXunRole selectOneByExampleSelective(@Param("example") ZhiXunRoleExample example, @Param("selective") ZhiXunRole.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role
     *
     * @mbg.generated
     */
    List<ZhiXunRole> selectByExampleSelective(@Param("example") ZhiXunRoleExample example, @Param("selective") ZhiXunRole.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role
     *
     * @mbg.generated
     */
    List<ZhiXunRole> selectByExample(ZhiXunRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role
     *
     * @mbg.generated
     */
    ZhiXunRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ZhiXunRole.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role
     *
     * @mbg.generated
     */
    ZhiXunRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role
     *
     * @mbg.generated
     */
    ZhiXunRole selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ZhiXunRole record, @Param("example") ZhiXunRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ZhiXunRole record, @Param("example") ZhiXunRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ZhiXunRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ZhiXunRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ZhiXunRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_role
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}