package zjc.zhixun.db.domain;

import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class TMessages31Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_messages_31
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_messages_31
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_messages_31
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_messages_31
     *
     * @mbg.generated
     */
    public TMessages31Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_messages_31
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_messages_31
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_messages_31
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_messages_31
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_messages_31
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_messages_31
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_messages_31
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_messages_31
     *
     * @mbg.generated
     */
    public TMessages31Example orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_messages_31
     *
     * @mbg.generated
     */
    public TMessages31Example orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_messages_31
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_messages_31
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_messages_31
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_messages_31
     *
     * @mbg.generated
     */
    public static Criteria newAndCreateCriteria() {
        TMessages31Example example = new TMessages31Example();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_messages_31
     *
     * @mbg.generated
     */
    public TMessages31Example when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_messages_31
     *
     * @mbg.generated
     */
    public TMessages31Example when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_messages_31
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andIdEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andIdNotEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andIdGreaterThanColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andIdGreaterThanOrEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andIdLessThanColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andIdLessThanOrEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMidIsNull() {
            addCriterion("_mid is null");
            return (Criteria) this;
        }

        public Criteria andMidIsNotNull() {
            addCriterion("_mid is not null");
            return (Criteria) this;
        }

        public Criteria andMidEqualTo(Long value) {
            addCriterion("_mid =", value, "mid");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andMidEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_mid = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMidNotEqualTo(Long value) {
            addCriterion("_mid <>", value, "mid");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andMidNotEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_mid <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMidGreaterThan(Long value) {
            addCriterion("_mid >", value, "mid");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andMidGreaterThanColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_mid > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMidGreaterThanOrEqualTo(Long value) {
            addCriterion("_mid >=", value, "mid");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andMidGreaterThanOrEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_mid >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMidLessThan(Long value) {
            addCriterion("_mid <", value, "mid");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andMidLessThanColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_mid < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMidLessThanOrEqualTo(Long value) {
            addCriterion("_mid <=", value, "mid");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andMidLessThanOrEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_mid <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMidIn(List<Long> values) {
            addCriterion("_mid in", values, "mid");
            return (Criteria) this;
        }

        public Criteria andMidNotIn(List<Long> values) {
            addCriterion("_mid not in", values, "mid");
            return (Criteria) this;
        }

        public Criteria andMidBetween(Long value1, Long value2) {
            addCriterion("_mid between", value1, value2, "mid");
            return (Criteria) this;
        }

        public Criteria andMidNotBetween(Long value1, Long value2) {
            addCriterion("_mid not between", value1, value2, "mid");
            return (Criteria) this;
        }

        public Criteria andFromIsNull() {
            addCriterion("_from is null");
            return (Criteria) this;
        }

        public Criteria andFromIsNotNull() {
            addCriterion("_from is not null");
            return (Criteria) this;
        }

        public Criteria andFromEqualTo(String value) {
            addCriterion("_from =", value, "from");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andFromEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_from = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFromNotEqualTo(String value) {
            addCriterion("_from <>", value, "from");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andFromNotEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_from <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFromGreaterThan(String value) {
            addCriterion("_from >", value, "from");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andFromGreaterThanColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_from > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFromGreaterThanOrEqualTo(String value) {
            addCriterion("_from >=", value, "from");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andFromGreaterThanOrEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_from >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFromLessThan(String value) {
            addCriterion("_from <", value, "from");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andFromLessThanColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_from < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFromLessThanOrEqualTo(String value) {
            addCriterion("_from <=", value, "from");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andFromLessThanOrEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_from <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFromLike(String value) {
            addCriterion("_from like", value, "from");
            return (Criteria) this;
        }

        public Criteria andFromNotLike(String value) {
            addCriterion("_from not like", value, "from");
            return (Criteria) this;
        }

        public Criteria andFromIn(List<String> values) {
            addCriterion("_from in", values, "from");
            return (Criteria) this;
        }

        public Criteria andFromNotIn(List<String> values) {
            addCriterion("_from not in", values, "from");
            return (Criteria) this;
        }

        public Criteria andFromBetween(String value1, String value2) {
            addCriterion("_from between", value1, value2, "from");
            return (Criteria) this;
        }

        public Criteria andFromNotBetween(String value1, String value2) {
            addCriterion("_from not between", value1, value2, "from");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("_type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("_type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Byte value) {
            addCriterion("_type =", value, "type");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andTypeEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_type = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Byte value) {
            addCriterion("_type <>", value, "type");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andTypeNotEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_type <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Byte value) {
            addCriterion("_type >", value, "type");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andTypeGreaterThanColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_type > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("_type >=", value, "type");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andTypeGreaterThanOrEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_type >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Byte value) {
            addCriterion("_type <", value, "type");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andTypeLessThanColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_type < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Byte value) {
            addCriterion("_type <=", value, "type");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andTypeLessThanOrEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_type <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Byte> values) {
            addCriterion("_type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Byte> values) {
            addCriterion("_type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Byte value1, Byte value2) {
            addCriterion("_type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("_type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTargetIsNull() {
            addCriterion("_target is null");
            return (Criteria) this;
        }

        public Criteria andTargetIsNotNull() {
            addCriterion("_target is not null");
            return (Criteria) this;
        }

        public Criteria andTargetEqualTo(String value) {
            addCriterion("_target =", value, "target");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andTargetEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_target = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTargetNotEqualTo(String value) {
            addCriterion("_target <>", value, "target");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andTargetNotEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_target <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTargetGreaterThan(String value) {
            addCriterion("_target >", value, "target");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andTargetGreaterThanColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_target > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTargetGreaterThanOrEqualTo(String value) {
            addCriterion("_target >=", value, "target");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andTargetGreaterThanOrEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_target >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTargetLessThan(String value) {
            addCriterion("_target <", value, "target");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andTargetLessThanColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_target < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTargetLessThanOrEqualTo(String value) {
            addCriterion("_target <=", value, "target");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andTargetLessThanOrEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_target <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTargetLike(String value) {
            addCriterion("_target like", value, "target");
            return (Criteria) this;
        }

        public Criteria andTargetNotLike(String value) {
            addCriterion("_target not like", value, "target");
            return (Criteria) this;
        }

        public Criteria andTargetIn(List<String> values) {
            addCriterion("_target in", values, "target");
            return (Criteria) this;
        }

        public Criteria andTargetNotIn(List<String> values) {
            addCriterion("_target not in", values, "target");
            return (Criteria) this;
        }

        public Criteria andTargetBetween(String value1, String value2) {
            addCriterion("_target between", value1, value2, "target");
            return (Criteria) this;
        }

        public Criteria andTargetNotBetween(String value1, String value2) {
            addCriterion("_target not between", value1, value2, "target");
            return (Criteria) this;
        }

        public Criteria andLineIsNull() {
            addCriterion("_line is null");
            return (Criteria) this;
        }

        public Criteria andLineIsNotNull() {
            addCriterion("_line is not null");
            return (Criteria) this;
        }

        public Criteria andLineEqualTo(Integer value) {
            addCriterion("_line =", value, "line");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andLineEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_line = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLineNotEqualTo(Integer value) {
            addCriterion("_line <>", value, "line");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andLineNotEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_line <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLineGreaterThan(Integer value) {
            addCriterion("_line >", value, "line");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andLineGreaterThanColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_line > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLineGreaterThanOrEqualTo(Integer value) {
            addCriterion("_line >=", value, "line");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andLineGreaterThanOrEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_line >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLineLessThan(Integer value) {
            addCriterion("_line <", value, "line");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andLineLessThanColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_line < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLineLessThanOrEqualTo(Integer value) {
            addCriterion("_line <=", value, "line");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andLineLessThanOrEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_line <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLineIn(List<Integer> values) {
            addCriterion("_line in", values, "line");
            return (Criteria) this;
        }

        public Criteria andLineNotIn(List<Integer> values) {
            addCriterion("_line not in", values, "line");
            return (Criteria) this;
        }

        public Criteria andLineBetween(Integer value1, Integer value2) {
            addCriterion("_line between", value1, value2, "line");
            return (Criteria) this;
        }

        public Criteria andLineNotBetween(Integer value1, Integer value2) {
            addCriterion("_line not between", value1, value2, "line");
            return (Criteria) this;
        }

        public Criteria andSearchableKeyLike(String value) {
            addCriterion("_searchable_key like", value, "searchableKey");
            return (Criteria) this;
        }

        public Criteria andSearchableKeyNotLike(String value) {
            addCriterion("_searchable_key not like", value, "searchableKey");
            return (Criteria) this;
        }

        public Criteria andDtIsNull() {
            addCriterion("_dt is null");
            return (Criteria) this;
        }

        public Criteria andDtIsNotNull() {
            addCriterion("_dt is not null");
            return (Criteria) this;
        }

        public Criteria andDtEqualTo(LocalDateTime value) {
            addCriterion("_dt =", value, "dt");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andDtEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_dt = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDtNotEqualTo(LocalDateTime value) {
            addCriterion("_dt <>", value, "dt");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andDtNotEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_dt <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDtGreaterThan(Timestamp value) {
            addCriterion("_dt >", value, "dt");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andDtGreaterThanColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_dt > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("_dt >=", value, "dt");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andDtGreaterThanOrEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_dt >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDtLessThan(Timestamp value) {
            addCriterion("_dt <", value, "dt");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andDtLessThanColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_dt < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("_dt <=", value, "dt");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andDtLessThanOrEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_dt <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDtIn(List<LocalDateTime> values) {
            addCriterion("_dt in", values, "dt");
            return (Criteria) this;
        }

        public Criteria andDtNotIn(List<LocalDateTime> values) {
            addCriterion("_dt not in", values, "dt");
            return (Criteria) this;
        }

        public Criteria andDtBetween(Timestamp value1, Timestamp value2) {
            addCriterion("_dt between", value1, value2, "dt");
            return (Criteria) this;
        }

        public Criteria andDtNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("_dt not between", value1, value2, "dt");
            return (Criteria) this;
        }
        public Criteria andDtLike(String value) {
            addCriterion("_dt like", value, "dt");
            return (Criteria) this;
        }

        public Criteria andDtNotLike(String value) {
            addCriterion("_dt not like", value, "dt");
            return (Criteria) this;
        }

        public Criteria andContentTypeIsNull() {
            addCriterion("_content_type is null");
            return (Criteria) this;
        }

        public Criteria andContentTypeIsNotNull() {
            addCriterion("_content_type is not null");
            return (Criteria) this;
        }

        public Criteria andContentTypeEqualTo(Integer value) {
            addCriterion("_content_type =", value, "contentType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andContentTypeEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_content_type = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andContentTypeNotEqualTo(Integer value) {
            addCriterion("_content_type <>", value, "contentType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andContentTypeNotEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_content_type <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andContentTypeGreaterThan(Integer value) {
            addCriterion("_content_type >", value, "contentType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andContentTypeGreaterThanColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_content_type > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andContentTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("_content_type >=", value, "contentType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andContentTypeGreaterThanOrEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_content_type >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andContentTypeLessThan(Integer value) {
            addCriterion("_content_type <", value, "contentType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andContentTypeLessThanColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_content_type < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andContentTypeLessThanOrEqualTo(Integer value) {
            addCriterion("_content_type <=", value, "contentType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andContentTypeLessThanOrEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_content_type <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andContentTypeIn(List<Integer> values) {
            addCriterion("_content_type in", values, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeNotIn(List<Integer> values) {
            addCriterion("_content_type not in", values, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeBetween(Integer value1, Integer value2) {
            addCriterion("_content_type between", value1, value2, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("_content_type not between", value1, value2, "contentType");
            return (Criteria) this;
        }

        public Criteria andToIsNull() {
            addCriterion("_to is null");
            return (Criteria) this;
        }

        public Criteria andToIsNotNull() {
            addCriterion("_to is not null");
            return (Criteria) this;
        }

        public Criteria andToEqualTo(String value) {
            addCriterion("_to =", value, "to");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andToEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_to = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andToNotEqualTo(String value) {
            addCriterion("_to <>", value, "to");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andToNotEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_to <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andToGreaterThan(String value) {
            addCriterion("_to >", value, "to");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andToGreaterThanColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_to > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andToGreaterThanOrEqualTo(String value) {
            addCriterion("_to >=", value, "to");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andToGreaterThanOrEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_to >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andToLessThan(String value) {
            addCriterion("_to <", value, "to");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andToLessThanColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_to < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andToLessThanOrEqualTo(String value) {
            addCriterion("_to <=", value, "to");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria andToLessThanOrEqualToColumn(TMessages31WithBLOBs.Column column) {
            addCriterion(new StringBuilder("_to <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andToLike(String value) {
            addCriterion("_to like", value, "to");
            return (Criteria) this;
        }

        public Criteria andToNotLike(String value) {
            addCriterion("_to not like", value, "to");
            return (Criteria) this;
        }

        public Criteria andToIn(List<String> values) {
            addCriterion("_to in", values, "to");
            return (Criteria) this;
        }

        public Criteria andToNotIn(List<String> values) {
            addCriterion("_to not in", values, "to");
            return (Criteria) this;
        }

        public Criteria andToBetween(String value1, String value2) {
            addCriterion("_to between", value1, value2, "to");
            return (Criteria) this;
        }

        public Criteria andToNotBetween(String value1, String value2) {
            addCriterion("_to not between", value1, value2, "to");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_messages_31
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        private TMessages31Example example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        protected Criteria(TMessages31Example example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public TMessages31Example example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table t_messages_31
             *
             * @mbg.generated
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_messages_31
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_messages_31
         *
         * @mbg.generated
         */
        void example(zjc.zhixun.db.domain.TMessages31Example example);
    }
}